### PR TITLE
Create Issue on this repo using Github API.

### PR DESCRIPTION
**Pull request by DeadSpoon18**
Added backend route to create issue using github api.

### CODE REVIEW

**Comment by DeadSpoon18** [comment]
why this check failed??

**Comment by AasthaGithub** [comment]
That's an error in Actions Config, don't worry won't bother the code.

**Review by AasthaGithub — CHANGES_REQUESTED** [review]
Awesome ✨ Just make the title & commit message more descriptive, referring the respective issue that's open & you're good to go.

**Comment by AasthaGithub** [comment]
@DeadSpoon18  are you working on this: https://github.com/AasthaGithub/Elemento/issues/85  as you commented earlier ?

**Comment by DeadSpoon18** [comment]
No sorry, I am not working on that issue right now.
And how can I edit commits I can't figure out.

**Comment by AasthaGithub** [comment]
Okay no worries. The PR solves https://github.com/AasthaGithub/Elemento/issues/84 making issue end point as required. Merging now. Thanks for contributing.

**Pull request merged**
